#!/bin/sh
set -e

exec 1>&2 2>/dev/null

test "$1" = "-" && src="cat" || src="xclip -o"

rofi="rofi -dmenu -yoffset 30 -location 2"

pag() {                                                 \
    sed -e 1d                                           \
        -e 's; _\([A-Z]\); \1;p'                        \
        -e '/^$/d' -e '/^-->/d'                         \
    | eval $rofi -l 20 -p 'Done'
}

phrase="$($src | eval $rofi -markup -p 'Lookup: ')"
{
    sdcv -n --utf8-input --utf8-output "$phrase"
    printf "Urban\n"
    links -dump "https://www.urbandictionary.com/define.php?term=$phrase" \
        | sed -n '1,/Top def/d;/Get the mug/q;p'
} | pag
