#!/bin/sh
set -e

test -z "$1" && {
    echo "usage: $0 file_extension"
    exit 1
}

getpath() {
    locate -e -0 -r '\.'$1'$' \
        | du -bh --files0-from=- \
        | sort -h -k1 | cut --output-delimiter=: -f1,2- \
        | dmenu -nf white -l 40 | cut -d: -f2- || exit 1
}

exec llppac "$(getpath "$1")"
