#!/bin/sh
set -e

out="$(basename "$1")"
dir="$(dirname "$1")"
expr >/dev/null "$2" : "/.*" && src="$2" || src="$PWD/$2"
shift 2
expr >/dev/null "$*" : '.* -pp ' && {
    ef=$(mktemp)
    trap 'test -n "$ef" && rm -f "$ef"' 0
    cd >/dev/null $dir && ocamlc 2>$ef "$@" -o $out $src
    rc=$?
    sed 1>&2 "s;File \"\([^\"]*\)\"\(.*\)$;File $src\2;" $ef
    exit $rc
} || {
    cd >/dev/null $dir && ocamlc "$@" -o $out $src
}
