#!/bin/sh

set -e

CACHEDIR=$HOME/.cache/llpp
caspsuf=
type=

die() {
    echo "$1" >&2
    exit 1
}

executable_p() {
    command -v "$1" >/dev/null 2>&1
}

maketext() {
    cat >"$CACHEDIR/fonts/text" <<EOF
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
abcdefghizklmnopqrstwxyz
ABCDEFGHIZKLMNOPQRSTWXYZ
\`1234567890-=\\
~!@#\$%^&*()_+|
[];',./
{}:"<>?

EOF
}

md5of="$1"
trap 'test -n "$casp" && rm -f "$casp"' 0

test -d "$CACHEDIR" || die "cache directory '$CACHEDIR' does not exist"
while getopts m:t:f opt; do
    case $opt in
        m) mime=$OPTARG;;
        t) type=$OPTARG;;
        f) force=1;;
        ?) die "usage: $0 [-m mime/type] [-t filter] [-f] path";;
    esac
done
shift $(($OPTIND - 1))
test -z "$1" && die "usage $0: path"

test -z "$type" && {
    $ft=$(file -L --mime-type -b "$1") || die "$ft"
}

case $ft in
    application/x-gzip | application/x-compress) dc=zcat;;
    application/x-xz) dc=xzcat;;
    application/x-bzip2) dc=bzcat;;
    *) unset dc || true;;
esac

filt='"${dc-cat}" "$1" |'

if test -z "$type"; then
    test -z "$dc" || ft=$(file -L --mime-type -bz "$1") || die "$ft"

    mime=${mime:-$ft}
    case $mime in
        application/postscript) type=ps;;
        application/pdf) type=pdf;;
        image/vnd.djvu) type=djvu;;
        text/html) type=html;;
        application/msword) type=word;;
        application/vnd.openxmlformats-officedocument.*  \
            | application/vnd.ms-powerpoint              \
            | application/vnd.ms-excel                   \
            | application/vnd.oasis.opendocument.*) type=uno;;
        image/svg+xml) type=svg;;
        image/png | image/jpeg) test -n "$dc" && type="image" || type="image2";;
        image/*) type=image;;
        application/x-dvi) type=dvi;;
        application/x-font-ttf | application/vnd.ms-opentype) type=font;;
        *) die "unhandled file type: '$mime'";;
    esac
fi

case $type in
    ps) conv='ps2pdf - "$casp"';;
    image2|pdf) test -z "$dc" && exec llpp "$@" || conv='cat >"$casp"';;
    djvu) conv='djvups - | ps2pdf - "$casp"';;
    html) {
        test -n "$dc" && die "can not convert compressed '$mime'"
        unset filt
        conv='prince "$1" -o "$casp"'
    };;
    word) {
        if executable_p unoconv && test -z "$dc"; then
            unset filt
            conv='unoconv -o "$casp" "$1"'
        else
            conv='antiword -m 8859-1.txt -a a4 - >"$casp"'
        fi
    };;
    uno) {
        test -n "$dc" && die "can not convert compressed '$mime'"
        unset filt
        conv='unoconv -o "$casp" "$1"'
    };;
    svg) {
        executable_p rsvg-convert                        \
            && conv='rsvg-convert -f pdf -o "$casp"'     \
            || conv='inkscape -z -A "$casp" -'
    };;
    font) {
        if test -e "$2"; then
            arg="$2"
        else
            arg="--waterfall $CACHEDIR/fonts/text"
            maketext
        fi
        # https://mail.gnome.org/archives/gtk-i18n-list/2010-June/msg00000.html
        eval $filt cat >$CACHEDIR/fonts/font
        cat >$CACHEDIR/fonts/fonts.conf <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<dir>$CACHEDIR/fonts/</dir>
	<cachedir>$CACHEDIR/fonts/</cachedir>
	<config></config>
</fontconfig>
EOF
        unset filt
        conv='FONTCONFIG_PATH=$CACHEDIR/fonts/ pango-view -q $arg -o $casp'
        caspsuf=.pdf
    };;
    fcfont) {
        if test -e "$2"; then
            arg="$2"
        else
            arg="--waterfall $CACHEDIR/fonts/text"
            maketext
        fi
        conv='pango-view --font="$1" -q $arg -o $casp'
        caspsuf=.pdf
        md5of=/dev/null
        filt=
        force=1
    };;
    image) conv='convert - pdf:"$casp"';;
    dvi) {
        test -n "$dc" && die "can not convert compressed '$mime'"
        unset filt
        conv='dvipdf "$1" "$casp"'
    };;
    *) die "unhandled filter type: '$type'";;
esac

hash=$(md5sum "$md5of") || die "$hash"
casp=$CACHEDIR/${hash%% *}$caspsuf
(test -n "$force" -o ! -e "$casp") && eval "$filt" "$conv"

exec llpp -origin "$@" "$casp"
