#!/bin/sh

set -e

CACHEDIR=$HOME/.cache/llpp

die() {
    echo "$1" >&2
    exit 1
}

executable_p() {
    command -v $1 >/dev/null 2>&1
}

trap '! test -z $casp && rm -f $casp' 0

test -d $CACHEDIR || die "cache directory $CACHEDIR does not exist"
while getopts m: opt; do
    case "$opt" in
        m) mime="$OPTARG";;
        ?)
        die "usage: $0 [-m mime/type] path";
        exit 1;;
    esac
done
shift $(($OPTIND - 1))
test -z "$1" && die "usage $0: path"

ft=$(file -L --mime-type -b "$1") || die "$ft"

case $ft in
    application/x-gzip) dc=zcat;;
    application/x-xz) dc=xzcat;;
    application/x-bzip2) dc=bzcat;;
    *) unset dc || true;;
esac

test -z $dc || ft=$(file -L --mime-type -bz "$1") || die "$ft"

filt='${dc-cat} "$1" |'

mime=${mime:-$ft}
case $mime in
    application/postscript) conv='ps2pdf - $casp';;
    application/pdf) test -z $dc && exec llpp "$@" || conv='cat >$casp';;
    image/vnd.djvu) conv='djvups - | ps2pdf - $casp';;
    text/html) {
        ! test -z $dc && die "can not convert compressed $mime"
        unset filt
        conv='prince "$1" -o $casp'
    };;
    application/msword) {
        if executable_p unoconv && test -z $dc; then
            unset filt
            conv='unoconv -o $casp "$1"'
        else
            conv='antiword -m 8859-1.txt -a a4 - >$casp'
        fi
    };;
    application/vnd.openxmlformats-officedocument.*) {
        ! test -z $dc && die "can not convert compressed $mime"
        unset filt
        conv='unoconv -o $casp "$1"'
    };;
    image/svg+xml) {
        executable_p rsvg-convert \
            && conv='rsvg-convert -f pdf -o $casp' \
            || conv='inkscape -z -A $casp -'
    };;
    image/*) conv='convert - pdf:$casp';;
    application/x-dvi) {
        ! test -z $dc && die "can not convert compressed $mime"
        unset filt
        conv='dvipdf $1 $casp'
    };;
    *) die "unhandled file type: $mime";;
esac

hash=$(md5sum "$1") || die "$hash"
casp="$CACHEDIR/${hash%% *}"
test -e $casp || eval "$filt" "$conv"

exec llpp -origin "$@" $casp
