#!/bin/sh

#set -x
set -e

h=$(readlink -f $(dirname $0))
r=$(readlink -f $h/..)
t=$r/tbs
d=MD5

export OCAMLRUNPARAM=b

if test $h = $PWD; then
    mkdir -p build
    cd build
fi

if ! md5sum --status -c $d; then
    md5sum $h/build.ml $h/tbs $t/tbs.cma >$d.tmp
    ocamlc.opt -o build.cmo -c -g -I $t $h/build.ml
    ocamlc.opt -g -thread -I $t unix.cma threads.cma tbs.cma build.cmo -o b
    mv $d.tmp $d
fi

mupdf=/home/malc/x/bld/mupdf
mupdf=/home/malc/x/rcs/darcs/mupdf/mupdf/
mupdf=/home/malc/x/rcs/svn/sumatrapdf-read-only/mupdf
cc=gcc
ccopt="-Wall -Werror -I$mupdf" # -Wno-unused-function -Wno-unused"
targets="llpp" #test testgl

lpath=$mupdf/build/linux-ppc-release/
lpath=$mupdf/build/release

./b -O src:$h -r -O ccopt:"$ccopt" -O cc:"$cc" \
-O "mupdflibpath:$lpath" \
$* $targets
