#!/bin/sh

#set -x
set -e

h=$(readlink -f $(dirname $0))
r=$(readlink -f $h/..)
t=$r/tbs
d=MD5

export OCAMLRUNPARAM=b

if test $h = $PWD; then
    mkdir -p build
    cd build
fi

if ! md5sum --status -c $d; then
    md5sum $h/build.ml $h/tbs $t/tbs.cma >$d.tmp
    ocamlc.opt -o build.cmo -c -g -I $t $h/build.ml
    ocamlc.opt -g -thread -I $t unix.cma threads.cma tbs.cma build.cmo -o b
    mv $d.tmp $d
fi

mupdf=/home/malc/x/rcs/svn/sumatrapdf-read-only/mupdf
mupdf=/home/malc/x/rcs/git/mupdf
cc=gcc-4.6.0
ccopt="-std=c89 -Wall -Werror -I$mupdf/fitz -I$mupdf/pdf"
ccopt="$ccopt $(freetype-config --cflags) -include ft2build.h"
targets="llpp"
libs="-lmupdf -lfitz -lopenjpeg -ljbig2dec -ljpeg -lz -lfreetype -lfontconfig"
ccopt="$ccopt -maltivec -O -D_GNU_SOURCE"

lpath=$mupdf/build/release

./b -O src:$h -r -O ccopt:"$ccopt" -O cc:"$cc" \
-O "mupdflibpath:$lpath" \
-O "libs:$libs" \
$* $targets
