#!/bin/sh

#set -x
set -e

h=$(readlink -f $(dirname $0))
t=$(readlink -f ..)/tbs
d=MD5

export OCAMLRUNPARAM=b

if test $h = $PWD; then
    mkdir -p build
    cd build
fi
bdir=$PWD

if ! md5sum --status -c $d; then
    md5sum $h/build.ml $h/tbs $t/tbs.cma >$d.tmp
    (cd $TMPDIR; ocamlc.opt -o $bdir/build.cmo -c -g -I $t $h/build.ml)
    ocamlc.opt -g -thread -I $t unix.cma threads.cma tbs.cma build.cmo -o b
    mv $d.tmp $d
fi

mupdf=/home/malc/x/rcs/git/mupdf
ccopt="-std=c89 -Wall -Werror"
ccopt="$ccopt -I$mupdf/include"
ccopt="$ccopt $(freetype-config --cflags) -include ft2build.h"
targets="llpp"
libs="-lmupdf"
libs="$libs -lopenjp2 -ljbig2dec -ljpeg -lz -lfreetype -lX11 -lcrypto"
if test $(hostname) = "linmac"; then
cc=gcc-4.6.0
ccopt="$ccopt -maltivec -D_GNU_SOURCE -DOBSCURED_OPT -DFFP -DUSE_FONTCONFIG"
else
cc=cc
ccopt="$ccopt -O -D_GNU_SOURCE -fPIC"
fi

lpath=$mupdf/build/release
#lpath=$mupdf/build/debug

./b -O src:$h -r -O ccopt:"$ccopt" -O cc:"$cc" \
-O "mupdflibpath:$lpath" \
-O "libs:$libs" \
$* $targets
