* TODO progressive zoom
* TODO Fixme
** TODO linknav + presentation (link might not fit the visible area)
   fullscreening while loading complex documents has visual quirks
* TODO outline for cbz
  file names? exif?
* TODO build.sh
** TODO Parallel builds
** TODO Avoid infinite recursion
** TODO Make isfresh work (properly) with multiple targets
** TODO Dependency issue
- cd /tmp
/tmp
- mkdir llpp
/tmp
- cd llpp
/tmp/llpp
- ln -sf ~/x/rcs/git/mupdf 
/tmp/llpp
- ~/xsrc/llpp/build.bash $PWD
[...]
wsi/x11/keysym2ucs.c -> wsi/x11/keysym2ucs.o
linking /tmp/llpp/llpp
File "_none_", line 1:
Error: Files /tmp/llpp/confstruct.cmo and /tmp/llpp/wsi/x11/wsi.cmo
       make inconsistent assumptions over interface Wsi
ocamlc -custom str.cma unix.cma -o /tmp/llpp/llpp ..." failed
ko 5 sec
*** Ugly workaround
    cd ~/src/llpp; bash build.bash /tmp/llpp
*** Workaround #2
Do not descend into llpp, but link mupdf into it and
build.bash with $PWD/llpp instead of just llpp.

That points to some issue with a way ocamlc locates modules.
