#!/bin/sh
set -e

url="$1"
test -z "$2" && {
    u=$(python3 -c "import urllib.parse; print (urllib.parse.unquote ('$url'))")
    out=$(echo "${u##*wiki/}.pdf" | tr / _)
} || out=$2

td=$(dirname $(readlink -f "$0"))

prince                                                  \
    --no-author-style                                   \
    --javascript                                        \
    --media screen                                      \
    -s file://$td/wiki2.css "$url" -o "$out"
